### ISSUE TITLE
Additional Complexity (Obstalce Chains)

### ISSUE THREAD

**Issue by ashes999** [deengames-prototypes/sword-of-eman#11]
Do we still need this at all?
- [ ] You'll need a LOT of content, not just three of each type.
- [ ] Put obstacle chains in the prologue
- [ ] Put obstacle chains in the intro
- [ ] Put obstacle chains in the final dungeon
