### ISSUE TITLE
Plug In Content

### ISSUE THREAD

**Issue by ashes999** [deengames-prototypes/sword-of-eman#15]
After #9.
- [ ] Pick a real ally (sprite, name)
- [ ] Assign a species to each map (cave, cliff, etc.) -- eg. bat cave, slime cave
- [ ] BOSSES! 
  - Generates in the cave/etc.
  - Once defeated, doesn't revive
- [ ] Consider more map types (cave/cliff) if needed.

**Comment by ashes999** [comment]
Replaced with wiki
