### ISSUE TITLE
Action RPG Core Gameplay

### ISSUE THREAD

**Issue by ashes999** [deengames-prototypes/sword-of-eman#2]
After #3.
- [x] VX Ace sprites  ~~or XP sprites? (LTTP style or Mana style?)~~
- [ ] Basic map with walls/floor tiles
- [ ] Walk around
- [ ] Press key to swing sword
- [ ] Keep master seed (hardcode for now, not random)
- [ ] Spawn random enemies
- [ ] Spawn random trees
- [ ] Touching enemies = ouch + bounceback
- [ ] Enemy attack animationz
- [ ] Keyboard shortcut (eg. `1`) to use an item
- [ ] Levelling up (all stats up)

**Comment by ashes999** [comment]
Replaced with wiki
