### ISSUE TITLE
v0.1 Backlog

### ISSUE THREAD

**Issue by ashes999** [deengames-prototypes/sword-of-eman#21]
**Goal:** 1-2 hours of solid gameplay with sufficient randomization to be different every time (from plot and characters down to the world itself). It must be a fun, complete game. No world map, it's just extra work and the game is cool without it.
- [x] **Decisions:**
  - [x] World map or no? (yes)
  - [x] ~~Action RPG or~~ hybrid (eg. mario RPG) or pure RPG? (hybrid)
  - [x] Mobile, if not ARPG? (no)
- [ ] Prototype of battle engine
  - [ ] Design: how is it fun? What's the core activity? What's the challenge? (The original SoM was enemies: bees poison, slimes duplicate, and you have to figure out how to beat them. Epic Battle heavily uses elements in attacks and resistance/immunity.)
  - [ ] Simple attack with one attack button
  - [ ] Light, medium, heavy (or low/medium/high)
  - [ ] L/M/H have a cost; max cost = 7
  - [ ] Three combos; two simple, and a complex (eg. LLH, MM, and LLMLH)
- [ ] Core location mechanics
  - [ ] Random player sprite
  - [ ] Basic map with walls/floor tiles
  - [ ] Walk around
  - [ ] Transition to world map (empty screen)
  - [ ] Generate hard-coded town
- [ ] Build world map
  - [ ] Empty world map with ocean and a single continent
  - [ ] Add town
  - [ ] Can walk around
  - [ ] Generate world locations for each key location
  - [ ] Generate a few non-key locations eg. Guardia Forest
  - [ ] Can enter locations
- [ ] Battle mechanics
  - [ ] Spawn random enemies at location
  - [ ] Spawn random trees at location
  - [ ] Touching enemies = battle screen with random number of monsters
  - [ ] Menu: attack, or ...nothing. Attacks.
  - [ ] Attack: bar with click range for 1.5x damage
  - [ ] Enemy attacks after your turn
  - [ ] Agility-based system, eg. you are 10, they are 5, you get two turns to their one
  - [ ] L/M/H or whatever it is
- [ ] Populate world
  - [ ] Classify each location as having one major species; generate THOSE enemies.
  - [ ] Add a second major species to each area (rarer, stronger)
  - [ ] Add a third, weaker species to each area. Generate those guys too.
- [ ] Final boss location (world map + location)
  - [ ] Final boss location locked until other quests are done
- [ ] Odds and Ends
  - [ ] Potions randomly drop from enemies
  - [ ] Menu, with character stats
  - [ ] Weapon skill levels
  - [ ] Items menu
  - [ ] Can use items: potions restore HP
  - [ ] Inn at town to revive HP
  - [ ] Titlescreen
  - [ ] New Game
  - [ ] New Game (named universe seed in URL)
