### ISSUE TITLE
v0.2 Backlog

### ISSUE THREAD

**Issue by ashes999** [deengames-prototypes/sword-of-eman#22]
- [ ] PCG plot (print only or store in data structures)
  - [ ] Pick three characters randomly (good, bad, and extra)
  - [ ] Pick a plot (one of two simple ones: sword power-up, or rescue the extra)
  - [ ] Generate locations based on the plot.
  - [ ] Assign an order to the locations. Should be linear.
  - [ ] Non-linear 1: add a junction. Instead of `A->B->C`, have `A->B->D` and `A->C->D`. (You can choose between `B` or `C`)
  - [ ] Non-linear 2: add an optional, non-plot-related extra dungeon. 
  - [ ] Add good loot or a nice power-up into it.
- [ ] Add a boss screen to 50% of dungeons
- [ ] Bosses never revive even if you leave the area and come back
  - [ ] Final boss is based on the key players
- [ ] Assign a difficulty to each location (based on quest order)
- [ ] Ramp up monster stats based on difficulty
- [ ] Distinct worlds. 
  - [ ] Eg. if building golems, some worlds have only gold/silver material.
  - [ ] Other worlds, you can get everything for the special, final weapons.
  - [ ] Some worlds are mostly, say, arctic or desert or mountains.
  - [ ] Some worlds have just lots of wolves. Dominant species.
  - [ ] Make sure combinations are sensible!
- [ ] Different map types: not just top-down
  - [ ] Purely side-view (ladders, jumping)
  - [ ] Partial top-down (only half the screen tall; parallax background
