### ISSUE TITLE
Basic PCG plot

### ISSUE THREAD

**Issue by ashes999** [deengames-prototypes/sword-of-eman#3]
BEFORE #2. Print everything as debug info and store data structures.
- [ ] Intro, main, and conclusion block
- [ ] Main block: acquire key item. It's 13 blocks total.
- [ ] Split into 3-4 sub-quests of 1-3 blocks each, plus, final consolidation quest
- [ ] Random power-up blocks: go to X and get some skill/power/power-up
- [ ] Put blocks in random order (some can be done concurrently)
- [ ] Generate key players
  - Final villain
  - A lackey or two
  - One helper/hero to guide you

**Comment by ashes999** [comment]
Replaced with wiki
