### ISSUE TITLE
World Building

### ISSUE THREAD

**Issue by ashes999** [deengames-prototypes/sword-of-eman#9]
After #3. Build maps.

Map blocks to maps.
- [ ] Cave map (eg. "get X orb from the cave" generates cave map)
- [ ] Cliff map

Other maps to generate:
- [ ] At least one town map
- [ ] At least one place (eg. water temple) your ally will coach you
- [ ] Starting map
- [ ] Link everything together nicely.

**Comment by ashes999** [comment]
Replaced with wiki.
